name: CI
on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: use nodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: install nodeJS
        run: npm ci
      - name: check code formatting
        run: npm run format:check
      - name: run automation tests
        run: npm test -- --coverage
        env:
            CI: true
      - name: build the project
        if: github.event.action == 'push'
        run: npm run build
      - name: Deploy to staging
        if: github.event.action == 'push'
        run: npx surge --project ./build --domain https://warlike-toy.surge.sh/
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}