name: CI
on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: node cache
        uses: actions/cache@v3.3.1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: use nodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: install nodeJS
        run: npm ci
      - name: check code formatting
        run: npm run format:check
      - name: run automation tests
        run: npm test -- --coverage
        env:
            CI: true
      - name: upload code coverage
        uses: actions/upload-artifact@v1
        with:
            name: code-coverage
            path: coverage
      - name: build the project
        if: github.event.action == 'push'
        run: npm run build
      - name: upload build
        if: github.event.action == 'push'
        uses: actions/upload-artifact@v1
        with:
            name: build
            path: build
      - name: create a release
        if: github.event.action == 'push' && github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to staging
        if: github.event.action == 'push'
        run: npx surge --project ./build --domain https://warlike-toy.surge.sh/
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}